window.SUPABASE_URL = 'https://tgrtesjyjwuzcqvfpadc.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncnRlc2p5and1emNxdmZwYWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMDA4OTMsImV4cCI6MjA5Mjg3Njg5M30.tp4e1nLfqR19IYgPxCuls5_DOVrFtX0uBqDqWKYNi7k';
